# Generated by Django 5.2.11 on 2026-02-27 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("branch", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                ("eligible", models.BooleanField()),
            ],
        ),
    ]
